FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY front_streamlit.py ./

EXPOSE 8501
CMD ["streamlit", "run", "front_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]