version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: eda_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./db:/app/db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: eda_frontend
    ports:
      - "8501:8501"
    environment:
      - GEMINI_API_KEY='GEMINI_API_KEY_HERE'
      - EDA_API_BASE=http://backend:8000
    volumes:
      - ./data:/app/data
    depends_on:
      - backend
